### PR TITLE
Modularize WiktionaryParser

### PR DESCRIPTION
**Pull request by fberlakovich**
This PR includes
* a massive refactoring (almost a complete rewrite) to modularize WiktionaryParser. The API is still the same and clients should not notice any difference
* a parser for Serbo-Croatian conjugation tables (inflections)

Initially I just wanted to contribute the inflections parser. However, since the old code is quite convoluted I couldn't just easily add code. So I ended up refactoring WiktionaryParser and implemented the inflection parser/processor on top. The new parser serves as an example of how the parsing can be extended. Existing clients should not notice any difference, as the API was only exended, but no existing API was modified.

The new architecture is as follows: The HTML soup is parsed by an extensible list of parser objects (e.g. ExamplesParser, DefinitionsParser, etc.). Once the parsers have extracted the interesting data, processor objects transform the data into its final form (e.g. they try to correlate etymologies with their definitions, just like the original code did). I reused most of the original code for implementing the parsers. Parsing and processing the Serbo-Croatian inflection tables looks as follows:

```
custom_parser = WiktionaryParser()
custom_parser.set_default_language('serbo-croatian')
custom_parser.set_content_parser("conjugation", serbocroatian.ConjugationsParser())
custom_parser.add_post_processor(serbocroatian.ConjugationsProcessor())
words = custom_parser.fetch("hodati", old_id=60892603)
```

This architecture should allow implementing more language specific stuff without opening up the core code all the time.

### CODE REVIEW

**Comment by Suyash458** [comment]
@fberlakovich Thanks a lot for your work! 😄 I like how you've modularized the parsers for different parts of speech. Since this is a huge change I'll take a while to look through but, overall it looks like a step in the right direction

**Comment by fberlakovich** [comment]
> @fberlakovich Thanks a lot for your work! 😄 I like how you've modularized the parsers for different parts of speech. Since this is a huge change I'll take a while to look through but, overall it looks like a step in the right direction

Sure, no worries. Thanks for all your work on this project!

**Comment by Suyash458** [comment]
@fberlakovich let's merge this into dev, I'd like to build on this too

**Comment by fberlakovich** [comment]
> @fberlakovich let's merge this into dev, I'd like to build on this too

Sure, is there anything I can do to help?

**Pull request merged**
